Repository angel-bridge/Front-end, pull requests merged in 2024-12, with the labels that each got.

#4 Design#3 all
  angel_bridge/package.json
  angel_bridge/src/style/global.css.ts
  angel_bridge/src/style/theme.css.ts
  angel_bridge/yarn.lock
Labels: 🎨 Design

#6 Init#5
  angel_bridge/.eslintrc.json
  angel_bridge/.prettierrc
  angel_bridge/package.json
  angel_bridge/public/file.svg
  angel_bridge/public/globe.svg
  angel_bridge/public/next.svg
  angel_bridge/public/vercel.svg
  angel_bridge/public/window.svg
  angel_bridge/src/app/Providers.tsx
  angel_bridge/src/app/favicon.ico
  angel_bridge/src/app/fonts/GeistMonoVF.woff
  angel_bridge/src/app/fonts/GeistVF.woff
  angel_bridge/src/app/globals.css
  angel_bridge/src/app/layout.tsx
  angel_bridge/src/app/page.tsx
  angel_bridge/yarn.lock
Labels: ⚙ Setting

#9 Etc#8
  angel_bridge/src/style/global.css.ts
  angel_bridge/src/style/theme.css.ts
  angel_bridge/tsconfig.json
Labels: ⚙ Setting

#13 Refactor#12 home
  angel_bridge/src/app/home/components/BlogArticles.tsx
  angel_bridge/src/app/home/components/Footer.tsx
  angel_bridge/src/app/home/components/Recommends.tsx
  angel_bridge/src/app/home/styles/Banner.css.ts
  angel_bridge/src/app/home/styles/BlogArticles.css.ts
  angel_bridge/src/app/home/styles/Footer.css.ts
  angel_bridge/src/app/home/styles/Recommends.css.ts
  angel_bridge/src/components/common/ProgramCard.css.ts
  angel_bridge/src/components/common/ProgramCard.tsx
Labels: 🔨 Refactor
