Repository angel-bridge/Front-end, pull requests merged in 2025-01, with the labels that each got.

#16 Feat/#15 home/api
  angel_bridge/src/api/banner.tsx
  angel_bridge/src/api/blog.tsx
  angel_bridge/src/api/education.tsx
  angel_bridge/src/api/instance.tsx
  angel_bridge/src/app/home/components/Banner.tsx
  angel_bridge/src/app/home/components/BlogArticles.tsx
  angel_bridge/src/app/home/components/Recommends.tsx
Labels: 📬 API

#20 Design#7 program
  angel_bridge/package.json
  angel_bridge/public/assets/search.svg
  angel_bridge/src/app/layout.tsx
  angel_bridge/src/app/program/page.tsx
  angel_bridge/src/program/PageComp.tsx
  angel_bridge/src/program/components/header/ProgramHeader.tsx
  angel_bridge/src/program/components/header/RecrutingBtn.tsx
  angel_bridge/src/program/components/header/Search.tsx
  angel_bridge/src/program/components/header/WillRecruteBtn.tsx.tsx
  angel_bridge/src/program/components/main/MainProgram.tsx
  angel_bridge/src/program/components/main/Programs.tsx
  angel_bridge/src/program/components/main/dummy.ts
  angel_bridge/src/program/components/main/styles/programmain.css.ts
  angel_bridge/src/program/page.tsx
  angel_bridge/src/program/styles/button.css.ts
  angel_bridge/src/program/styles/header.css.ts
  angel_bridge/src/program/styles/pageCompo.css.ts
  angel_bridge/src/program/styles/pagelayout.css.ts
  angel_bridge/src/program/styles/search.css.ts
Labels: 🎨 Design

#26 Design#22 performance status
  angel_bridge/package.json
  angel_bridge/src/app/status/page.tsx
  angel_bridge/src/app/status/pagelayout.css.ts
  angel_bridge/src/mypage/memberInfo/core/error.ts
  angel_bridge/src/status/assets/gray.svg
  angel_bridge/src/status/assets/green.svg
  angel_bridge/src/status/assets/modalCancel.svg
  angel_bridge/src/status/assets/orange.svg
  angel_bridge/src/status/assets/person.svg
  angel_bridge/src/status/assets/purple.svg
  angel_bridge/src/status/assets/red.svg
  angel_bridge/src/status/assets/ring.svg
  angel_bridge/src/status/components/BottomFrame.tsx
  angel_bridge/src/status/components/MissionCompleteStatus.tsx
  angel_bridge/src/status/components/MissionSubmitStatusCard.tsx
  angel_bridge/src/status/components/MissonCard.tsx
  angel_bridge/src/status/components/Notion.tsx
  angel_bridge/src/status/components/PieChartCard.tsx
  angel_bridge/src/status/components/StatusCard.tsx
  angel_bridge/src/status/components/UpperFrame.tsx
  angel_bridge/src/status/components/modal/LinkInput.tsx
  angel_bridge/src/status/components/modal/Modal.tsx
  angel_bridge/src/status/components/modal/SubmitModal.tsx
  angel_bridge/src/status/core/missionStatus.ts
  angel_bridge/src/status/core/modalType.ts
  angel_bridge/src/status/core/notion.ts
  angel_bridge/src/status/core/submitStatus.ts
  angel_bridge/src/status/store/useModal.tsx
  angel_bridge/src/status/styles/bottom.css.ts
  angel_bridge/src/status/styles/button.css.ts
  angel_bridge/src/status/styles/common.css.ts
  angel_bridge/src/status/styles/input.css.ts
  angel_bridge/src/status/styles/missionStatus.css.ts
  angel_bridge/src/status/styles/status.css.ts
  angel_bridge/src/style/theme.css.ts
  angel_bridge/yarn.lock
Labels: 🎨 Design

#33 Design#32 inquiry
  angel_bridge/src/inquiry/assets/ASK.png
  angel_bridge/src/inquiry/assets/ASK.svg
  angel_bridge/src/inquiry/assets/FQA.png
  angel_bridge/src/inquiry/assets/faqsvg.svg
  angel_bridge/src/inquiry/components/Container.tsx
  angel_bridge/src/inquiry/components/PageComponent.tsx
  angel_bridge/src/inquiry/core/inquiry.ts
  angel_bridge/src/inquiry/styles/container.css.ts
Labels: 🎨 Design

#30 Api#24 programpage
  angel_bridge/package.json
  angel_bridge/src/app/program/[educationId]/page.tsx
  angel_bridge/src/components/common/ProgramCard.tsx
  angel_bridge/src/program/api/hooks/useGetAllPrograms.tsx
  angel_bridge/src/program/api/hooks/useGetDetailProgram.tsx
  angel_bridge/src/program/api/hooks/useGetOngoings.tsx
  angel_bridge/src/program/api/hooks/useGetSearch.tsx
  angel_bridge/src/program/api/hooks/useGetUpcoming.tsx
  angel_bridge/src/program/api/utils/getAllProgram.ts
  angel_bridge/src/program/api/utils/getDetailProgram.ts
  angel_bridge/src/program/api/utils/getOngoingPrograms.ts
  angel_bridge/src/program/api/utils/getSearch.ts
  angel_bridge/src/program/api/utils/getUpcomingProgram.ts
  angel_bridge/src/program/assets/leftIc.svg
  angel_bridge/src/program/assets/rightIc.svg
  angel_bridge/src/program/components/header/RecrutingBtn.tsx
  angel_bridge/src/program/components/header/Search.tsx
  angel_bridge/src/program/components/header/WillRecruteBtn.tsx.tsx
  angel_bridge/src/program/components/main/MainProgram.tsx
  angel_bridge/src/program/components/main/PageNation.tsx
  angel_bridge/src/program/components/main/Programs.tsx
  angel_bridge/src/program/components/main/styles/pagenation.css.ts
  angel_bridge/src/program/components/main/styles/programmain.css.ts
  angel_bridge/src/program/detailPage/assets/alarm.svg
  angel_bridge/src/program/detailPage/assets/banner.png
  angel_bridge/src/program/detailPage/assets/calendar.svg
  angel_bridge/src/program/detailPage/assets/money.svg
  angel_bridge/src/program/detailPage/assets/purchase.svg
  angel_bridge/src/program/detailPage/assets/time.svg
  angel_bridge/src/program/detailPage/components/Banner.tsx
  angel_bridge/src/program/detailPage/components/BannerAndPurchase.tsx
  angel_bridge/src/program/detailPage/components/DescriptionTitle.tsx
  angel_bridge/src/program/detailPage/components/ProgramCard.tsx
  angel_bridge/src/program/detailPage/components/ProgramDescription.tsx
  angel_bridge/src/program/detailPage/components/ProgramSummary.tsx
  angel_bridge/src/program/detailPage/components/PurchaseBtn.tsx
  angel_bridge/src/program/detailPage/core/description.ts
  angel_bridge/src/program/detailPage/styles/description.css.ts
  angel_bridge/src/program/detailPage/styles/detail.css.ts
  angel_bridge/src/program/detailPage/styles/programcard.css.ts
  angel_bridge/src/program/detailPage/styles/purchase.css.ts
  angel_bridge/src/program/store/useProgramStore.ts
  angel_bridge/src/program/styles/button.css.ts
  angel_bridge/src/program/types/dataType.ts
  angel_bridge/src/program/types/detailTypes.ts
  angel_bridge/yarn.lock
Labels: 📬 API

#36 Hotfix#35
  angel_bridge/src/program/api/utils/getAllProgram.ts
  angel_bridge/src/program/api/utils/getOngoingPrograms.ts
  angel_bridge/src/program/api/utils/getUpcomingProgram.ts
  angel_bridge/src/program/components/main/MainProgram.tsx
  angel_bridge/src/program/types/dataType.ts
Labels: 🚑️ hotfix

#28 Design#14 history page
  angel_bridge/public/assets/defaultThumbnail.png
  angel_bridge/src/app/history/components/Contents.tsx
  angel_bridge/src/app/history/components/MyLectureCard.tsx
  angel_bridge/src/app/history/components/PageTitle.tsx
  angel_bridge/src/app/history/components/TakenButton.tsx
  angel_bridge/src/app/history/components/TakingButton.tsx
  angel_bridge/src/app/history/components/WillTakeButton.tsx
  angel_bridge/src/app/history/components/Wrapper.tsx
  angel_bridge/src/app/history/page.tsx
  angel_bridge/src/app/history/styles/Contents.css.ts
  angel_bridge/src/app/history/styles/MyLectureCard.css.ts
  angel_bridge/src/app/history/styles/PageTitle.css.ts
  angel_bridge/src/app/history/styles/Wrapper.css.ts
  angel_bridge/src/app/history/styles/button.css.ts
  angel_bridge/src/components/common/Button.css.ts
  angel_bridge/src/components/common/Button.tsx
Labels: 🎨 Design

#39 Api#38 program
  angel_bridge/src/app/program/page.tsx
  angel_bridge/src/components/common/ProgramCard.css.ts
  angel_bridge/src/components/common/ProgramCard.tsx
  angel_bridge/src/program/api/hooks/useGetBanner.tsx
  angel_bridge/src/program/api/utils/getBanner.ts
  angel_bridge/src/program/components/header/ProgramBanner.tsx
  angel_bridge/src/program/components/main/MainProgram.tsx
  angel_bridge/src/program/components/main/PageNation.tsx
  angel_bridge/src/program/components/main/Programs.tsx
  angel_bridge/src/program/components/main/styles/pagenation.css.ts
  angel_bridge/src/program/components/main/styles/programmain.css.ts
  angel_bridge/src/program/detailPage/styles/programcard.css.ts
  angel_bridge/src/program/styles/header.css.ts
  angel_bridge/src/program/styles/pagelayout.css.ts
Labels: 📬 API

#44 Api#27 history page
  angel_bridge/src/api/authInstance.tsx
  angel_bridge/src/api/banner.tsx
  angel_bridge/src/api/blog.tsx
  angel_bridge/src/api/education.tsx
  angel_bridge/src/api/instance.tsx
  angel_bridge/src/app/history/api/hooks/useGetTakenPrograms.tsx
  angel_bridge/src/app/history/api/hooks/useGetTakingPrograms.tsx
  angel_bridge/src/app/history/api/hooks/useGetWillTakePrograms.tsx
  angel_bridge/src/app/history/api/utils/getTakenPrograms.ts
  angel_bridge/src/app/history/api/utils/getTakingPrograms.ts
  angel_bridge/src/app/history/api/utils/getWillTakePrograms.ts
  angel_bridge/src/app/history/components/Contents.tsx
  angel_bridge/src/app/history/components/MyLectureCard.tsx
  angel_bridge/src/app/history/components/PageTitle.tsx
  angel_bridge/src/app/history/components/TakenButton.tsx
  angel_bridge/src/app/history/components/TakingButton.tsx
  angel_bridge/src/app/history/components/WillTakeButton.tsx
  angel_bridge/src/app/history/components/Wrapper.tsx
  angel_bridge/src/app/history/styles/Contents.css.ts
  angel_bridge/src/app/history/styles/PageTitle.css.ts
  angel_bridge/src/app/history/styles/Wrapper.css.ts
  angel_bridge/src/program/api/utils/getAllProgram.ts
  angel_bridge/src/program/api/utils/getBanner.ts
  angel_bridge/src/program/api/utils/getDetailProgram.ts
  angel_bridge/src/program/api/utils/getOngoingPrograms.ts
  angel_bridge/src/program/api/utils/getSearch.ts
  angel_bridge/src/program/api/utils/getUpcomingProgram.ts
  angel_bridge/src/program/types/dataType.ts
Labels: 📬 API

#47 Design#46
  angel_bridge/src/api/instance.ts
  angel_bridge/src/mypage/memberInfo/assets/greencheck.svg
  angel_bridge/src/mypage/memberInfo/components/Info.tsx
  angel_bridge/src/mypage/memberInfo/components/SaveChangeBtn.tsx
  angel_bridge/src/mypage/memberInfo/components/SnackBar.tsx
  angel_bridge/src/mypage/memberInfo/styles/snackbar.css.ts
  angel_bridge/src/program/api/utils/getAllProgram.ts
  angel_bridge/src/program/api/utils/getBanner.ts
  angel_bridge/src/program/api/utils/getDetailProgram.ts
  angel_bridge/src/program/api/utils/getOngoingPrograms.ts
  angel_bridge/src/program/api/utils/getSearch.ts
  angel_bridge/src/program/api/utils/getUpcomingProgram.ts
  angel_bridge/src/program/assets/preparingIc.svg
  angel_bridge/src/program/assets/searchIc.svg
  angel_bridge/src/program/components/main/EmpthySearch.tsx
  angel_bridge/src/program/components/main/EmpthyView.tsx
  angel_bridge/src/program/components/main/MainProgram.tsx
  angel_bridge/src/program/detailPage/components/BannerAndPurchase.tsx
  angel_bridge/src/program/detailPage/components/PurchaseBtn.tsx
  angel_bridge/src/program/detailPage/styles/programcard.css.ts
  angel_bridge/src/program/detailPage/styles/purchase.css.ts
  angel_bridge/src/program/styles/empthyview.css.ts
Labels: ✨ Feature, 🎨 Design

#49 48#etc
  angel_bridge/src/api/authInstance.tsx
  angel_bridge/src/api/banner.tsx
  angel_bridge/src/api/blog.tsx
  angel_bridge/src/api/education.tsx
  angel_bridge/src/app/history/components/PageTitle.tsx
  angel_bridge/src/app/payments/fail/page.tsx
  angel_bridge/src/app/payments/success/page.tsx
  angel_bridge/src/payments/ExampleCode.tsx
  angel_bridge/src/payments/FailurePage.tsx
  angel_bridge/src/payments/PaymentContainer.tsx
  angel_bridge/src/payments/SuccessPage.tsx
Labels: 🌏 Deploy

#41 Design#40 footer
  angel_bridge/src/app/home/styles/Footer.css.ts
  angel_bridge/src/common/assets/instagram_button.svg
  angel_bridge/src/common/assets/mail_button.svg
  angel_bridge/src/common/assets/notion_button.svg
  angel_bridge/src/common/components/Footer.tsx
Labels: 🎨 Design

#53 52#qa programpage
  angel_bridge/next.config.ts
  angel_bridge/package.json
  angel_bridge/public/assets/kakao_login.png
  angel_bridge/src/api/auth.tsx
  angel_bridge/src/api/authInstance.ts
  angel_bridge/src/api/education.tsx
  angel_bridge/src/app/home/components/BlogArticles.tsx
  angel_bridge/src/app/home/components/LoginModal.tsx
  angel_bridge/src/app/home/components/Recommends.tsx
  angel_bridge/src/app/home/components/SignupModal.tsx
  angel_bridge/src/app/home/styles/Footer.css.ts
  angel_bridge/src/app/layout.tsx
  angel_bridge/src/app/login/assets/profile_img.jpg
  angel_bridge/src/app/login/components/KakaoLogin.tsx
  angel_bridge/src/app/login/components/ProfileButton.tsx
  angel_bridge/src/app/login/hooks/usePostLogout.tsx
  angel_bridge/src/app/login/hooks/usePostMemberInfo.tsx
  angel_bridge/src/app/login/page.tsx
  angel_bridge/src/app/login/styles/LoginButton.ts
  angel_bridge/src/app/login/styles/ProfileButton.css.ts
  angel_bridge/src/app/login/utils/postLogout.ts
  angel_bridge/src/app/login/utils/postMemberInfo.ts
  angel_bridge/src/app/program/[educationId]/page.tsx
  angel_bridge/src/common/components/Header.tsx
  angel_bridge/src/components/common/ProgramCard.css.ts
  angel_bridge/src/inquiry/core/inquiry.ts
  angel_bridge/src/lib/cookies.ts
  angel_bridge/src/mypage/payment/styles/container.css.ts
  angel_bridge/src/program/api/hooks/useGetAllPrograms.tsx
  angel_bridge/src/program/components/main/MainProgram.tsx
  angel_bridge/src/program/components/main/Programs.tsx
  angel_bridge/src/program/components/main/styles/programmain.css.ts
  angel_bridge/src/program/detailPage/components/Banner.tsx
  angel_bridge/src/program/detailPage/components/BannerAndPurchase.tsx
  angel_bridge/src/program/detailPage/components/ProgramCard.tsx
  angel_bridge/src/program/detailPage/components/ProgramDescription.tsx
  angel_bridge/src/program/detailPage/components/PurchaseBtn.tsx
  angel_bridge/src/program/detailPage/styles/purchase.css.ts
  angel_bridge/src/program/styles/header.css.ts
  angel_bridge/src/program/styles/pageCompo.css.ts
  angel_bridge/src/program/styles/pagelayout.css.ts
  angel_bridge/src/program/styles/search.css.ts
  angel_bridge/src/style/global.css.ts
  angel_bridge/yarn.lock
Labels: 📐 QA

#56 Qa#55
  angel_bridge/src/app/home/styles/LoginModal.css.ts
  angel_bridge/src/mypage/payment/components/EmpthyView.tsx
  angel_bridge/src/mypage/payment/components/Wrapper.tsx
  angel_bridge/src/payments/Checkout.tsx
  angel_bridge/src/program/api/utils/getDetailProgram.ts
  angel_bridge/src/program/detailPage/components/ProgramCard.tsx
  angel_bridge/src/program/detailPage/components/ProgramDescription.tsx
  angel_bridge/src/program/detailPage/components/PurchaseBtn.tsx
  angel_bridge/src/program/detailPage/styles/purchase.css.ts
  angel_bridge/src/program/types/detailTypes.ts
Labels: 📐 QA

#58 [ deploy ] qa 반영 pr
  angel_bridge/src/app/home/styles/LoginModal.css.ts
  angel_bridge/src/mypage/payment/components/EmpthyView.tsx
  angel_bridge/src/mypage/payment/components/Wrapper.tsx
  angel_bridge/src/payments/Checkout.tsx
  angel_bridge/src/program/api/utils/getDetailProgram.ts
  angel_bridge/src/program/detailPage/components/ProgramCard.tsx
  angel_bridge/src/program/detailPage/components/ProgramDescription.tsx
  angel_bridge/src/program/detailPage/components/PurchaseBtn.tsx
  angel_bridge/src/program/detailPage/styles/purchase.css.ts
  angel_bridge/src/program/types/detailTypes.ts
Labels: 📐 QA

#59 [ design ] 배너 비율 변경
  angel_bridge/src/program/styles/header.css.ts
Labels: 📐 QA

#60 [ QA ]
  angel_bridge/src/program/styles/header.css.ts
Labels: 📐 QA

#61 Qa#55
  angel_bridge/src/payments/Checkout.tsx
  angel_bridge/src/payments/PaymentContainer.tsx
  angel_bridge/src/payments/SuccessPage.tsx
  angel_bridge/src/payments/successpage.css.ts
Labels: 📐 QA

#62 [ Deploy ]
  angel_bridge/src/payments/Checkout.tsx
  angel_bridge/src/payments/PaymentContainer.tsx
  angel_bridge/src/payments/SuccessPage.tsx
  angel_bridge/src/payments/successpage.css.ts
Labels: 🌏 Deploy

#67 Hotfix#66
  angel_bridge/src/mypage/api/hooks/useGetPayment.tsx
  angel_bridge/src/mypage/api/hooks/usePostCancelPayments.tsx
  angel_bridge/src/mypage/api/utils/postCancelPayment.ts
  angel_bridge/src/mypage/payment/components/CancelBtn.tsx
  angel_bridge/src/mypage/payment/components/Content.tsx
  angel_bridge/src/mypage/payment/components/Wrapper.tsx
Labels: 🚑️ hotfix

#68 [ deploy ]
  angel_bridge/src/mypage/api/hooks/useGetPayment.tsx
  angel_bridge/src/mypage/api/hooks/usePostCancelPayments.tsx
  angel_bridge/src/mypage/api/utils/postCancelPayment.ts
  angel_bridge/src/mypage/payment/components/CancelBtn.tsx
  angel_bridge/src/mypage/payment/components/Content.tsx
  angel_bridge/src/mypage/payment/components/Wrapper.tsx
Labels: 🌏 Deploy

#69 Hotfix#66
  angel_bridge/src/mypage/payment/components/Content.tsx
  angel_bridge/src/mypage/payment/components/Wrapper.tsx
  angel_bridge/src/mypage/payment/styles/container.css.ts
Labels: 📐 QA

#70 [ Deploy ]
  angel_bridge/src/mypage/payment/components/Content.tsx
  angel_bridge/src/mypage/payment/components/Wrapper.tsx
  angel_bridge/src/mypage/payment/styles/container.css.ts
Labels: 🌏 Deploy
